set_global_assignment -name VERILOG_MACRO "CORENAME=\"JTDD\""
set_global_assignment -name VERILOG_MACRO "GAMETOP=jtdd_game"
set_global_assignment -name VERILOG_MACRO "MISTTOP=jtdd_mist"
set_global_assignment -name VERILOG_MACRO "STEREO_GAME=1"
set_global_assignment -name VERILOG_MACRO "COLORW=4"
# set_global_assignment -name VERILOG_MACRO "AVATARS=1"
